### ISSUE TITLE
Clarify transient usage

### ISSUE THREAD

**Issue by hura** [purnam/purnam#10]
Note that in clojure you MUST capture the return of `assoc!` calls etc in transients:

http://clojure.org/transients

However, your examples in the docs seem to suggest that this is not necessary for your transients. This should probably be added to the documentation if that's the case.

**Comment by zcaudate** [comment]
Can you explain more? I’m not sure what "capture the return” means (in terms of should it be hidden?). Also, note that we are not dealing with immutable datastructures but with js objects and arrays. They are mutable by default.

**Comment by hura** [comment]
I mean that you're example would not work correctly if it were used in Clojure since you still have to pass around the return value of every `(dis)assoc!` call and then at the end pass that returned value into `persistent!`.

**Comment by hura** [comment]
Also see:
http://stackoverflow.com/questions/29684803/why-inserting-1000-000-values-in-a-transient-map-in-clojure-yields-a-map-with-8

Anyways, it's probably a non-issue since most people will understand that it'll work fine for mutable objects. Thus closing.
