### ISSUE TITLE
Update/Clarify Readme

### ISSUE THREAD

**Issue by the-kenny** [purnam/purnam#7]
Most of the examples in the Readme seem outdated nowadays. It would be nice if you could clarify these in order to prevent confusion when people without much ClojureScript experience look at your library.

For example:

```
function square(x){
  return {value: x.value * x.value};
}
```

Can be written in pure ClojureScript as:

```
(defn square [x]  
  (js-obj "value" (* x.value x.value)))
```
or
```
(defn square [x] 
  #js {:value (* x.value x.value)})
```

**Comment by zcaudate** [comment]
I'm revisiting this library in the next couple of days.... with the latest version of cljs, it seems that there a quite a bit of catching up to do =)
