### ISSUE TITLE
compilation warning with clojurescript "0.0-2411": cljs.core/+, all arguments must be numbers

### ISSUE THREAD

**Issue by viebel** [purnam/purnam#8]
This piece of code creates a compilation warning with clojurescript "0.0-2411"
```
(def a js/aa)
(+ (? a.b.c) 2)
``` 

`WARNING: cljs.core/+, all arguments must be numbers, got [#{nil clj-nil} number] instead.`

**Comment by viebel** [comment]
do you intend to solve the compilation warnings? It's quite ennoying :smile:

**Comment by zcaudate** [comment]
Thanks for the reminder. I'm on a bit of an extended holiday and really haven't been able to look at this. I'll be travelling for another month and then will be quite busy with work.

Are you able to spend time with this? It shouldn't take too much time - just figuring where the code is breaking.. I'm presuming that there has been a change in the cljs compiler. If you can create an example project of this issue then raise an issue with the clojurescript project to have someone look at it, then it may be solved quite quickly.

**Comment by viebel** [comment]
Here is a small piece of code that reproduces the compilation warning:

    (set! js/aa #js {})
    (def a js/aa)
    (! a.b.c 5555)
    (+ 2 (? a.b.c))


The problem is that `?` is returns `nil` in case that some piece of the hierarchy doesn't exist. So for the compiler, it is not guaranteed that `(? a.b.c)` is a number.

I would be happy to try to fix your code, but I need some guidance.

**Comment by zcaudate** [comment]
Sorry for the unresponsiveness... I was trekking and did not have reception for about a week....

Okay... I'm gunna get onto this.

**Comment by zcaudate** [comment]
I'm asking on the mailing list: https://groups.google.com/forum/#!topic/clojurescript/2ue-RvKXCSM

hopefully, someone more expert can take a look at it. feel free to add to the thread

**Comment by zcaudate** [comment]
I think this issue has been resolved.... see above mailing list: clojurescript "0.0-2629" and above work fine without the warnings. I tried it out and it seems to be fine. Let me know if I can close this issue =)
